### ISSUE TITLE
Different launch method

### ISSUE THREAD

**Issue by ardittristan** [elanandkumar/vscode-product-icon-theme#2]
Since v1_47 you can also enable proposed api via argv.json if you add this:

```json
"enable-proposed-api": [
	"ElAnandKumar.el-vsc-product-icon-theme"
]
```

this method should probably be mentioned in the readme since it doesn't require launching VSCode through the command line

**Comment by pankh-thewing** [comment]
Thanks @ardittristan ,
I'll look into it and will update accordingly.

**Comment by elanandkumar** [comment]
Hello @ardittristan,
The new version is published now. It is out of preview and can be launched without proposed api now.

Thanks.
