### ISSUE TITLE
Product icon themes are now stable

### ISSUE THREAD

**Issue by aeschli** [elanandkumar/vscode-product-icon-theme#3]
Thanks for trying the new product icon theme APIs.

The APIs are now stable for 1.53 and `--enable-proposed-api` is no longer needed.

Note: When publishing, use the latest version of `vsce`. Your extension with then automatically get the `product-icon-theme` tag and will be easy to be found by users.

**Comment by elanandkumar** [comment]
Thanks @aeschli,
I have update the extension (v0.1.7) and readme is also updated accordingly.
